# Linear Spin-Wave Theory

In [10]:
import numpy as np

$$H=\sum_i[J_1\mathbf S_i\cdot\mathbf S_{i+1}+J_2\mathbf S_i\cdot\mathbf S_{i+2}].$$


In [11]:
# set the parameters
lambda_ = 10 # wave length
J1 = -1.0 # J1

n_periods = 1 # number of periods in the lattice
n_sites = n_periods * lambda_ # total number of sites

S = 1 # quantum spin
z = 2 # 

Q = 2 * np.pi / lambda_ # wave vector
J2 = -J1 / (4 * np.cos(Q))


print(f'J1 : {J1}')
print(f'J2 : {J2}')
print(f'n_sites : {n_sites}')
print(f'S : {S}')
print(f'z : {z}')


J1 : -1.0
J2 : 0.3090169943749474
n_sites : 10
S : 1
z : 2


In [12]:
theta = Q * np.arange(n_sites) # phase angle
phi = np.zeros(n_sites) # azimuthal angle

In [13]:
def U_r_inv(theta, phi):
    return np.array([
        [np.cos(theta) * np.cos(phi), -np.sin(phi), np.sin(theta) * np.cos(phi)],
        [np.cos(theta) * np.sin(phi), np.cos(phi), np.sin(theta) * np.sin(phi)],
        [-np.sin(theta), 0.0, np.cos(theta)]
    ])

In [14]:
U_inv = np.array([
    U_r_inv(theta[r], phi[r])
    for r in range(n_sites)
])

print(U_inv.shape)

(10, 3, 3)


In [15]:
def F_rs(U_inv, r, s):
    return U_inv[r].T @ U_inv[s]

In [16]:
F_J1 = np.empty((n_sites, 3, 3))

for r in range(n_sites):
    s = (r + 1) % n_sites
    F_J1[r] = F_rs(U_inv, r, s)

In [17]:
F_J2 = np.empty((n_sites, 3, 3))

for r in range(n_sites):
    s = (r + 2) % n_sites
    F_J2[r] = F_rs(U_inv, r, s)

In [18]:
print("F J1:")
print(F_J1[0])

print("\nF J2:")
print(F_J2[0])

F J1:
[[ 0.80901699  0.          0.58778525]
 [ 0.          1.          0.        ]
 [-0.58778525  0.          0.80901699]]

F J2:
[[ 0.30901699  0.          0.95105652]
 [ 0.          1.          0.        ]
 [-0.95105652  0.          0.30901699]]


$$
\frac{1}{NS^2}\frac{d^2E_{\rm cl}}{dQ^2}
=-J_1\cos Q-4J_2\cos(2Q).
$$

Dengan $c=\cos Q=-J_1/(4J_2)$ dan $\cos(2Q)=2c^2-1$,

$$
\begin{aligned}
\frac{1}{NS^2}\frac{d^2E_{\rm cl}}{dQ^2}
&=-J_1c-4J_2(2c^2-1)\\
&=\frac{J_1^2}{4J_2}-\frac{J_1^2}{2J_2}+4J_2\\
&=\frac{16J_2^2-J_1^2}{4J_2}>0.
\end{aligned}
$$

$$J_2>0,\qquad |J_1|<4J_2.$$

Nilai kode:

$$S=1,\quad J_1=1,\quad J_2=0.5,$$

$$\cos Q=-\frac{1}{4(0.5)}=-\frac12
\Rightarrow
Q=\arccos(-1/2)=\frac{2\pi}{3}=2.0944.$$